// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {template} from '../models';
import {main} from '../models';
import {ssh} from '../models';

export function AcceptSSHHostKey(arg1:string):Promise<void>;

export function ApplyTemplate(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CloseTerminal(arg1:number):Promise<void>;

export function ConfirmFrontendReady(arg1:number):Promise<void>;

export function DeleteSSHProfile(arg1:string):Promise<Array<ssh.Profile>>;

export function DeleteTemplate(arg1:string):Promise<Array<template.Template>>;

export function GetCurrentDirectory():Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetLoadedSessionData():Promise<session.SessionData>;

export function GetSSHProfiles():Promise<Array<ssh.Profile>>;

export function GetSSHSecretBackend():Promise<string>;

export function GetSSHTerminalLabel(arg1:number):Promise<string>;

export function GetTemplates():Promise<Array<template.Template>>;

export function InitializeTerminal(arg1:number):Promise<void>;

export function ListDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function ListSSHKeys():Promise<Array<ssh.SSHKeyInfo>>;

export function OpenPathInExplorer(arg1:string):Promise<void>;

export function RejectSSHHostKey(arg1:string):Promise<void>;

export function ReloadTemplates():Promise<Array<template.Template>>;

export function RemoteGetFileContent(arg1:number,arg2:string):Promise<string>;

export function RemoteGetHomeDir(arg1:number):Promise<string>;

export function RemoteListDirectory(arg1:number,arg2:string):Promise<Array<main.FileInfo>>;

export function RemoveTerminalState(arg1:number):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SaveCurrentSession():Promise<void>;

export function SaveSSHProfile(arg1:string):Promise<Array<ssh.Profile>>;

export function SaveTemplate(arg1:string):Promise<Array<template.Template>>;

export function SetSSHPassword(arg1:string,arg2:string):Promise<void>;

export function StartSSHTerminal(arg1:string):Promise<number>;

export function StartTerminal(arg1:string):Promise<number>;

export function StartTerminalWithOptions(arg1:string,arg2:string):Promise<number>;

export function GetTerminalTmuxStatus(arg1:number):Promise<Record<string, any>>;

export function ToggleFavorite(arg1:string):Promise<Array<template.Template>>;

export function UpdateSSHProfile(arg1:string):Promise<Array<ssh.Profile>>;

export function UpdateTemplate(arg1:string):Promise<Array<template.Template>>;

export function UpdateTerminalState(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:string):Promise<void>;

export function KillTmuxSession(arg1:string):Promise<void>;

export function WriteToTerminal(arg1:number,arg2:string):Promise<void>;

export function SecretStoreState():Promise<string>;

export function SetupSecretMasterPassword(arg1:string):Promise<void>;

export function UnlockSecrets(arg1:string):Promise<void>;

export function LockSecrets():Promise<void>;

export function ChangeSecretMasterPassword(arg1:string,arg2:string):Promise<void>;

export function ListFIDOChallenges():Promise<Array<any>>;

export function UnlockSecretsFIDO(arg1:string):Promise<void>;

export function EnrollFIDO(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetRecordInput(arg1:boolean):Promise<void>;

export function RecordInputEnabled():Promise<boolean>;
