// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptSSHHostKey(arg1) {
  return window['go']['main']['App']['AcceptSSHHostKey'](arg1);
}

export function ApplyTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyTemplate'](arg1, arg2, arg3);
}

export function CloseSSHTerminalFull(arg1) {
  return window['go']['main']['App']['CloseSSHTerminalFull'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ConfirmFrontendReady(arg1) {
  return window['go']['main']['App']['ConfirmFrontendReady'](arg1);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteSSHProfile(arg1) {
  return window['go']['main']['App']['DeleteSSHProfile'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetHistoryHostnames() {
  return window['go']['main']['App']['GetHistoryHostnames']();
}

export function GetHistoryStats(arg1) {
  return window['go']['main']['App']['GetHistoryStats'](arg1);
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetLoadedSessionData() {
  return window['go']['main']['App']['GetLoadedSessionData']();
}

export function GetTerminalFolders() {
  return window['go']['main']['App']['GetTerminalFolders']();
}

export function SaveTerminalFolder(arg1) {
  return window['go']['main']['App']['SaveTerminalFolder'](arg1);
}

export function UpdateTerminalFolder(arg1) {
  return window['go']['main']['App']['UpdateTerminalFolder'](arg1);
}

export function DeleteTerminalFolder(arg1) {
  return window['go']['main']['App']['DeleteTerminalFolder'](arg1);
}

export function GetSSHProfiles() {
  return window['go']['main']['App']['GetSSHProfiles']();
}

export function GetSSHSecretBackend() {
  return window['go']['main']['App']['GetSSHSecretBackend']();
}

export function GetSSHTerminalLabel(arg1) {
  return window['go']['main']['App']['GetSSHTerminalLabel'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function ImportNoteFromLocal(arg1) {
  return window['go']['main']['App']['ImportNoteFromLocal'](arg1);
}

export function ImportNoteFromRemote(arg1, arg2) {
  return window['go']['main']['App']['ImportNoteFromRemote'](arg1, arg2);
}

export function InitializeTerminal(arg1) {
  return window['go']['main']['App']['InitializeTerminal'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListSSHKeys() {
  return window['go']['main']['App']['ListSSHKeys']();
}

export function OpenPathInExplorer(arg1) {
  return window['go']['main']['App']['OpenPathInExplorer'](arg1);
}

export function PurgeHistoryBefore(arg1) {
  return window['go']['main']['App']['PurgeHistoryBefore'](arg1);
}

export function ReconnectSSHTerminal(arg1) {
  return window['go']['main']['App']['ReconnectSSHTerminal'](arg1);
}

export function RejectSSHHostKey(arg1) {
  return window['go']['main']['App']['RejectSSHHostKey'](arg1);
}

export function RemoteGetFileContent(arg1, arg2) {
  return window['go']['main']['App']['RemoteGetFileContent'](arg1, arg2);
}

export function RemoteGetHomeDir(arg1) {
  return window['go']['main']['App']['RemoteGetHomeDir'](arg1);
}

export function RemoteListDirectory(arg1, arg2) {
  return window['go']['main']['App']['RemoteListDirectory'](arg1, arg2);
}

export function ReloadTemplates() {
  return window['go']['main']['App']['ReloadTemplates']();
}

export function RemoveTerminalState(arg1) {
  return window['go']['main']['App']['RemoveTerminalState'](arg1);
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['App']['RenameNote'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveCurrentSession() {
  return window['go']['main']['App']['SaveCurrentSession']();
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function SearchCommandHistory(arg1) {
  return window['go']['main']['App']['SearchCommandHistory'](arg1);
}

export function SaveSSHProfile(arg1) {
  return window['go']['main']['App']['SaveSSHProfile'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SetSSHPassword(arg1, arg2) {
  return window['go']['main']['App']['SetSSHPassword'](arg1, arg2);
}

export function StartSSHTerminal(arg1) {
  return window['go']['main']['App']['StartSSHTerminal'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['App']['UpdateTemplate'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StartTerminalWithOptions(arg1, arg2) {
  return window['go']['main']['App']['StartTerminalWithOptions'](arg1, arg2);
}

export function GetTerminalTmuxStatus(arg1) {
  return window['go']['main']['App']['GetTerminalTmuxStatus'](arg1);
}

export function UpdateSSHProfile(arg1) {
  return window['go']['main']['App']['UpdateSSHProfile'](arg1);
}

export function UpdateTerminalState(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateTerminalState'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function KillTmuxSession(arg1) {
  return window['go']['main']['App']['KillTmuxSession'](arg1);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function IsRecording(arg1) {
  return window['go']['main']['App']['IsRecording'](arg1);
}

export function ListRecordings() {
  return window['go']['main']['App']['ListRecordings']();
}

export function GetRecording(arg1) {
  return window['go']['main']['App']['GetRecording'](arg1);
}

export function DownloadAgg() {
  return window['go']['main']['App']['DownloadAgg']();
}

export function GetAggDownloadInfo() {
  return window['go']['main']['App']['GetAggDownloadInfo']();
}

export function DeleteRecording(arg1) {
  return window['go']['main']['App']['DeleteRecording'](arg1);
}

export function ExportRecordingScrubbed(arg1) {
  return window['go']['main']['App']['ExportRecordingScrubbed'](arg1);
}

export function ExportRecordingGIF(arg1) {
  return window['go']['main']['App']['ExportRecordingGIF'](arg1);
}

export function ExportRecordingTrimmed(arg1, arg2) {
  return window['go']['main']['App']['ExportRecordingTrimmed'](arg1, arg2);
}

export function ExportRecordingTrimmedGIF(arg1, arg2) {
  return window['go']['main']['App']['ExportRecordingTrimmedGIF'](arg1, arg2);
}

export function IsAggInstalled() {
  return window['go']['main']['App']['IsAggInstalled']();
}

export function IsHistoryTrackingEnabled() {
  return window['go']['main']['App']['IsHistoryTrackingEnabled']();
}

export function SetHistoryTracking(arg1) {
  return window['go']['main']['App']['SetHistoryTracking'](arg1);
}

export function SecretStoreState() {
  return window['go']['main']['App']['SecretStoreState']();
}

export function SetupSecretMasterPassword(arg1) {
  return window['go']['main']['App']['SetupSecretMasterPassword'](arg1);
}

export function UnlockSecrets(arg1) {
  return window['go']['main']['App']['UnlockSecrets'](arg1);
}

export function LockSecrets() {
  return window['go']['main']['App']['LockSecrets']();
}

export function ChangeSecretMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeSecretMasterPassword'](arg1, arg2);
}

export function ListFIDOChallenges() {
  return window['go']['main']['App']['ListFIDOChallenges']();
}

export function UnlockSecretsFIDO(arg1) {
  return window['go']['main']['App']['UnlockSecretsFIDO'](arg1);
}

export function EnrollFIDO(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EnrollFIDO'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRecordInput(arg1) {
  return window['go']['main']['App']['SetRecordInput'](arg1);
}

export function RecordInputEnabled() {
  return window['go']['main']['App']['RecordInputEnabled']();
}
